### ISSUE TITLE
Cannot start Meteor using Vagrant image

### ISSUE THREAD

**Issue by westjgames** [meteor-gazelle/vagrant#1]
The following message appears after starting meteor:

vagrant@gazelle:/var/www$ meteor run --settings settings.json
[[[[[ /var/www ]]]]]                          

=> Started proxy.                             

=> Meteor 1.2.1: React and Angular support, ECMAScript 2015, new faster build
system, and improvements to the Cordova integration for mobile apps.

This release is being downloaded in the background. Update your app to
Meteor 1.2.1 by running 'meteor update'.

Unexpected mongo exit code 1. Restarting.  
Unexpected mongo exit code 1. Restarting.  
Unexpected mongo exit code 1. Restarting.  
Can't start Mongo server.

**Comment by ghost** [comment]
According to online documentation, this should resolve itself.

If it does not, reopen this issue.
